# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cordova Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    env:
      ONEGINI_AUTOCONFIGURE: "false"

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    
    - name: "Set environmental variables"
      run: |
        echo "ONEGINI_SDK_CONFIGURATOR_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "ONEGINI_CONFIG_ANDROID_PATH=$GITHUB_WORKSPACE/onegini-config-android.zip" >> $GITHUB_ENV
        echo "JAVA_HOME=$JAVA_HOME_8_X64" >> $GITHUB_ENV
        echo "JAVA_HOME_8.0.312_x64=$JAVA_HOME_8_X64" >> $GITHUB_ENV

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

#     - name: Setup Android SDK
#       uses: android-actions/setup-android@v2

    - uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: |
          platforms;android-31
          system-images;android-31;google_apis;x86

    - run: npm install
    
    - name: Download onegini-sdk-configurator
      run: |
         curl -O -L https://github.com/onewelcome/sdk-configurator/releases/download/5.0.0/onegini-sdk-configurator-linux-64bit.zip > onegini-sdk-configurator-linux-64bit.zip
         unzip onegini-sdk-configurator-linux-64bit.zip
         ls
      shell: bash
      
    - run: npm run build
    
    - run: npm install -g cordova
    
    - run: cordova platform add android
    
    - run: cordova build --no-telemetry
      env:
        ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

#     - name: Use oxr463/setup-cordova
#       uses: oxr463/setup-cordova@0.0.3
#       with:
#         exec: |
#           cordova platform add android
    
#     - name: Run onegini-sdk-configurator
#       run: |
#          $GITHUB_WORKSPACE/onegini-sdk-configurator android --config $GITHUB_WORKSPACE/onegini-config-android.zip --app-dir $GITHUB_WORKSPACE/platforms/android -m app --debugDetection=false --rootDetection=false
#       shell: bash

#     - name: Use oxr463/setup-cordova
#       uses: oxr463/setup-cordova@0.0.3
#       with:
#         exec: |
#           cordova build --no-telemetry && \
#           cp "$(find . -name '*.apk')" .
